[package]
name = "hakiru-sentinel"
version = "0.1.0"
authors = ["ibochivincent-lang <ibochivincent-lang@users.noreply.github.com>"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }
interfaces = { path = "../interfaces" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
